name: aspotus-project

services:
  redis:
    image: redis:7.2.14-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Aspotus.Catalog.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5299
      ConnectionStrings__CatalogDb: Data Source=/data/catalog.db
      ConnectionStrings__Redis: redis:6379
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5299:5299"
    volumes:
      - ./data/catalog:/data
    networks:
      - backend

  orders-api:
    image: ${DOCKER_REGISTRY-}orders-api
    build:
      context: .
      dockerfile: Aspotus.Orders.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5115
      ConnectionStrings__OrdersDb: Data Source=/data/orders.db
    ports:
      - "5115:5115"
    volumes:
      - ./data/orders:/data
    networks:
      - backend

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Aspotus.Gateway/Dockerfile
    depends_on:
      - catalog-api
      - orders-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5230
      ConnectionStrings__DefaultConnection: Data Source=/data/gateway.db
      ReverseProxy__Clusters__catalog-cluster__Destinations__catalog-destination__Address: http://catalog-api:5299/
      ReverseProxy__Clusters__orders-cluster__Destinations__orders-destination__Address: http://orders-api:5115/
    ports:
      - "5230:5230"
    volumes:
      - ./data/gateway:/data
    networks:
      - backend

networks:
  backend:
